#!/bin/bash
#
#    10-sysinfo - generate the system information
#    Copyright (c) 2013 Nick Charlton
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

date=`date`
load=`cat /proc/loadavg | awk '{print $1}'`
memory_usage=`free -m | awk '/Mem:/ { total=$2 ; avail=$7 } END { printf("%3.1f%% (%0.2fGiB free)", (total-avail)/total*100, avail/1024)}'`
root_usage=`df -h / | awk '/\// {percent=$(NF-1); avail=$(NF-2); print percent " (" avail "iB free)"}'`
swap_usage=`free -m | awk '/Swap/ { printf("%3.1f%%", "exit !$2;$3/$2*100") }'`
users=`users | wc -w`
time=`uptime | grep -ohe 'up .*' | sed 's/,/\ hours/g' | awk '{ printf $2" "$3 }'`
processes=`ps aux | wc -l`
ip=`ip route get $(ip route show 0.0.0.0/0 | grep -oP 'via \K\S+') | grep -oP 'src \K\S+'`

echo "System information as of: $date"
echo
printf "%-16s%-32s%-16s%s\n" 'System load:' "$load" 'IP Address:' "$ip"
printf "%-16s%-32s%-16s%s\n" 'Memory load:' "$memory_usage" 'Uptime:' "$time"
printf "%-16s%-32s%-16s%s\n" 'Disk use:' "$root_usage" 'Swap use:' "$swap_usage"
printf "%-16s%-32s%-16s%s\n" 'Local users:' "$users" 'Processes:' "$processes"
echo

